- name: variables from files
  hosts: localhost
  vars_files:
    vars.yaml
  tasks:
  - name: print information
    ansible.builtin.debug:
      mas: "Hi! we are learning {{Course}} from {{Trainer}} Duration is {{Duration}}"