- name: data types
  hosts: local host
  vars:
    course: Devops with AWS #string
    Tools: # list
    - Linux
    - Shell
    - Ansible
    - Terraform
    Experience: # map or directory
      Devops: 3 # number
      AWS: 2
      Docker: 1