- name: data types
  hosts: localhost
  vars:
    course: Devops with AWS #string
    Tools: # list
    - Linux
    - Shell
    - Ansible
    - Terraform
    Experience: # map or directory
      Devops: 3 # number
      AWS: 2
      Docker: 1
    RealProject: true  # boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{course}}, Tools covered: {{Tools}}, Experience: is : {{Experience}} is real project : {{RealProject}}"