- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('ansible')}}"
   
- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"