- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('ansible')}}"
   
- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 1, 3, 5, 2, 4, 5]
  tasks:
  - name: remove duplicate numbers
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"


- name: min and max numbers
  hosts: localhost
  vars:
    ages: [14, 54, 33, 20]
  tasks:
  - name: min and max ages
    ansible.builtin.debug:
      msg: "min age: {{ ages | min }} and  max age: {{ ages | max }}"

- name: convert dictionary to items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs
      Course: Devops
      Trainer: shiva
      Duration: 12hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert: {{my_dict}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert: {{my_dict | dict2items}}"


- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Devops'}
    - {'key': 'Trainer', 'value': 'shiva'}
    - {'key': 'Duration', 'value': '12hrs'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert: {{my_list}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert: {{my_list | items2dict}}"






